/var/spool/slurmd/job73291/slurm_script: line 11: cd: SSL_VAN: No such file or directory

----------------------------------------------------------------------------
  cuda:
----------------------------------------------------------------------------
     Versions:
        cuda/10.2
        cuda/11.0
        cuda/11.2
        cuda/11.3
        cuda/11.4
        cuda/11.5
        cuda/11.6
        cuda/11.7
        cuda/11.8
        cuda/12.0

----------------------------------------------------------------------------
  For detailed information about a specific "cuda" package (including how to load the modules) use the module's full name.
  Note that names that have a trailing (E) are extensions provided by other modules.
  For example:

     $ module spider cuda/12.0
----------------------------------------------------------------------------

 


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:135: UserWarning: Found total gpus 2
  warnings.warn("Found total gpus {}".format(args.ngpus_per_node))
/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:155: UserWarning: 1 gpu 1
  warnings.warn(f"{args.rank} gpu {args.gpu}")
/home/karimimonsefi.1/SSL_VAN/commons/models/van_v4_122gl.py:11: UserWarning: embed_dims GL = [64, 128, 256, 512]
  warnings.warn(f'embed_dims GL = {embed_dims}')
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:155: UserWarning: 0 gpu 0
  warnings.warn(f"{args.rank} gpu {args.gpu}")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:157: UserWarning: Batch size is: 1 epochs 1000 and task is Task08_HepaticVessel
  warnings.warn(f"Batch size is: {args.batch_size} epochs {args.max_epochs} and task is {args.task}")
/home/karimimonsefi.1/SSL_VAN/commons/models/van_v4_122gl.py:11: UserWarning: embed_dims GL = [64, 128, 256, 512]
  warnings.warn(f'embed_dims GL = {embed_dims}')
/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/post/array.py:176: UserWarning: `to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.
  warnings.warn("`to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.")
/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/post/array.py:176: UserWarning: `to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.
  warnings.warn("`to_onehot=True/False` is deprecated, please use `to_onehot=num_classes` instead.")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:190: UserWarning: Total parameters count 67579560
  warnings.warn(f"Total parameters count {pytorch_total_params}")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:193: UserWarning: Total args.checkpoint True
  warnings.warn(f"Total args.checkpoint {args.checkpoint}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:6: UserWarning:  base_url is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel
  warnings.warn(f" base_url is {base_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:8: UserWarning:  output_url 1 is ./runs/MSD_new/test_log/output_False_False
  warnings.warn(f" output_url 1 is {output_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:9: UserWarning:  exists 1 is True
  warnings.warn(f" exists 1 is {os.path.exists(output_url)}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:13: UserWarning:  output_url 2 is ./runs/MSD_new/test_log/output_False_False/64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel
  warnings.warn(f" output_url 2 is {output_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:14: UserWarning:  exists 2 is True
  warnings.warn(f" exists 2 is {os.path.exists(output_url)}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:20: UserWarning:  Best url model is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel__best.pt, final model url is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel__final.pt
  warnings.warn(f" Best url model is {args.best_model_url}, final model url is {args.final_model_url}")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:190: UserWarning: Total parameters count 67579560
  warnings.warn(f"Total parameters count {pytorch_total_params}")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:193: UserWarning: Total args.checkpoint True
  warnings.warn(f"Total args.checkpoint {args.checkpoint}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:6: UserWarning:  base_url is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel
  warnings.warn(f" base_url is {base_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:8: UserWarning:  output_url 1 is ./runs/MSD_new/test_log/output_False_False
  warnings.warn(f" output_url 1 is {output_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:9: UserWarning:  exists 1 is True
  warnings.warn(f" exists 1 is {os.path.exists(output_url)}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:13: UserWarning:  output_url 2 is ./runs/MSD_new/test_log/output_False_False/64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel
  warnings.warn(f" output_url 2 is {output_url}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:14: UserWarning:  exists 2 is True
  warnings.warn(f" exists 2 is {os.path.exists(output_url)}")
/home/karimimonsefi.1/SSL_VAN/commons/util.py:20: UserWarning:  Best url model is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel__best.pt, final model url is 64-128-256-512_3-4-6-3_8-8-4-4_vae_inferer_valid_loader_VANV4122GL_Task08_HepaticVessel__final.pt
  warnings.warn(f" Best url model is {args.best_model_url}, final model url is {args.final_model_url}")
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:207: UserWarning: => loaded checkpoint 'True' (epoch 233) (bestacc 0.6867268681526184)
  warnings.warn("=> loaded checkpoint '{}' (epoch {}) (bestacc {})".format(
/home/karimimonsefi.1/SSL_VAN/MSD/main.py:207: UserWarning: => loaded checkpoint 'True' (epoch 233) (bestacc 0.6867268681526184)
  warnings.warn("=> loaded checkpoint '{}' (epoch {}) (bestacc {})".format(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:139: UserWarning: Writing Tensorboard logs to ./runs/MSD_new/test_log
  warnings.warn(f"Writing Tensorboard logs to {args.logdir}")
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:147: UserWarning: 0  Thu Aug 10 17:52:24 2023  Epoch: 233
  warnings.warn(f"{args.rank}  {time.ctime()}  Epoch: {epoch}")
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:147: UserWarning: 1  Thu Aug 10 17:52:24 2023  Epoch: 233
  warnings.warn(f"{args.rank}  {time.ctime()}  Epoch: {epoch}")
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:29: UserWarning: input size torch.Size([6, 1, 96, 96, 96])
  warnings.warn("input size {}".format(data.shape))
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:29: UserWarning: input size torch.Size([6, 1, 96, 96, 96])
  warnings.warn("input size {}".format(data.shape))
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 0/126  loss: 0.9109  time 19.37s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 1/126  loss: 0.9044  time 1.18s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 2/126  loss: 0.9059  time 1.09s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 3/126  loss: 0.9057  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 4/126  loss: 0.9089  time 1.04s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 5/126  loss: 0.9116  time 1.09s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 6/126  loss: 0.9216  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 7/126  loss: 0.9232  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 8/126  loss: 0.9247  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 9/126  loss: 0.9225  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 10/126  loss: 0.9221  time 1.06s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 11/126  loss: 0.9196  time 1.08s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 12/126  loss: 0.9210  time 1.02s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 13/126  loss: 0.9240  time 1.02s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 14/126  loss: 0.9246  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 15/126  loss: 0.9244  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 16/126  loss: 0.9288  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 17/126  loss: 0.9291  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 18/126  loss: 0.9288  time 1.09s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 19/126  loss: 0.9288  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 20/126  loss: 0.9285  time 1.02s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 21/126  loss: 0.9279  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 22/126  loss: 0.9285  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 23/126  loss: 0.9288  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 24/126  loss: 0.9283  time 1.06s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 25/126  loss: 0.9279  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 26/126  loss: 0.9298  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 27/126  loss: 0.9288  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 28/126  loss: 0.9284  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 29/126  loss: 0.9281  time 1.00s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 30/126  loss: 0.9276  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 31/126  loss: 0.9273  time 1.04s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 32/126  loss: 0.9282  time 1.01s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 33/126  loss: 0.9276  time 1.05s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 34/126  loss: 0.9272  time 1.03s
  warnings.warn(
/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py:51: UserWarning: Epoch 233/1000 35/126  loss: 0.9267  time 1.00s
  warnings.warn(
Traceback (most recent call last):
  File "/home/karimimonsefi.1/SSL_VAN/MSD/main.py", line 261, in <module>
    main()
  File "/home/karimimonsefi.1/SSL_VAN/MSD/main.py", line 137, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args,))
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/karimimonsefi.1/SSL_VAN/MSD/main.py", line 239, in main_worker
    accuracy = run_training(
  File "/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py", line 149, in run_training
    train_loss = train_epoch(
  File "/home/karimimonsefi.1/SSL_VAN/MSD/trainer.py", line 23, in train_epoch
    for idx, batch_data in enumerate(loader):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/nibabel/loadsave.py", line 87, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '../images/MSD/Task08_HepaticVessel/labbestelsTr/hepaticvessel_132.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/io/dictionary.py", line 131, in __call__
    data = self._loader(d[key], reader)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/io/array.py", line 213, in __call__
    img = reader.read(filename)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/data/image_reader.py", line 421, in read
    img = nib.load(name, **kwargs_)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/nibabel/loadsave.py", line 89, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '../images/MSD/Task08_HepaticVessel/labbestelsTr/hepaticvessel_132.nii.gz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x14ad17c0b670>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/karimimonsefi.1/miniconda3/lib/python3.9/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x14ad17c05e50>


